---
deployment:
  tasks:
    - export DEPLOYPATH=/home/portstew/pca/
    - /bin/cp -r * $DEPLOYPATH #copy all from root
    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    - $DEPLOYPATH/composer update
